algoritmo "contador1a10"
// =============================================================
// Algoritmo para contar de 0 a 10 usando a estrutura PARA.
//
// AUTOR: Gustavo Guanabara
// Curso COMPLETO disponivel GRATIS no site www.cursoemvideo.com
// =============================================================
var
  C: Inteiro
inicio
   Para C <- 10 ate 1 passo -1 faca
      EscrevaL(C)
   FimPara
fimalgoritmo
