algoritmo "Combinacoes"
// =============================================================
// Algoritmo para mostrar combinacoes possiveis entre os valores
// 1, 2 e 3.
//
// AUTOR: Gustavo Guanabara
// Curso COMPLETO disponivel GRATIS no site www.cursoemvideo.com
// =============================================================
var
  C1, C2 : Inteiro
inicio
   Para C1 := 1 ate 3 faca
      Para C2 := 1 ate 3 faca
         EscrevaL (C1, C2)
      FimPara
   FimPara
fimalgoritmo
